#数据库配置
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/vm_experiment
    username: root
    password: 123
server:
  port: 8081
#mybatis配置
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
# 文件上传配置
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB
#阿里云OSS文件上传
#aliyun:
#  oss:
#    endpoint: https://oss-cn-beijing.aliyuncs.com
#    bucket-name: tlia-web-management
